# Generated by Django 4.2.7 on 2025-08-01 09:08

from django.db import migrations, models
import lesion_analyzer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LesionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=lesion_analyzer.models.upload_to)),
                ('segmentation_mask', models.ImageField(blank=True, null=True, upload_to='masks/')),
                ('predicted_class', models.CharField(blank=True, choices=[('MEL', 'Melanoma'), ('NV', 'Melanocytic nevus'), ('BCC', 'Basal cell carcinoma'), ('AK', 'Actinic keratosis'), ('BKL', 'Benign keratosis'), ('DF', 'Dermatofibroma'), ('VASC', 'Vascular lesion'), ('SCC', 'Squamous cell carcinoma')], max_length=4)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
