# Generated by Django 5.2.5 on 2025-08-13 13:06

import lesion_analyzer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesion_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesionanalysis',
            name='segmented_region',
            field=models.ImageField(blank=True, null=True, upload_to='regions/'),
        ),
        migrations.AlterField(
            model_name='lesionanalysis',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=lesion_analyzer.models.upload_to),
        ),
    ]
